import type { MetaFunction } from '@remix-run/node';
import { json, LoaderFunction } from '@remix-run/node';
import { useLoaderData } from '@remix-run/react';
import { prisma } from '~/lib/db';
import { Program } from '@prisma/client'; // Importing the type generated by Prisma

export const meta: MetaFunction = () => {
  return [
    { title: 'aiOS HOMEPAGE' },
    { name: 'description', content: 'Welcome to aiOS!' },
  ];
};

export const loader: LoaderFunction = async () => {
  const programs = await prisma.program.findMany();
  return json(programs);
};

export default function Index() {
  const programs = useLoaderData<Program[]>();

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', lineHeight: '1.8' }}>
      <h1>Welcome to The Future: aiOS version 0.1</h1>
      <p>My Programs:</p>
      <ul>
        {programs.map((program) => (
          <li key={program.id}>
            <a href={`/programs/${program.id}`}>{program.programName}</a>
          </li>
        ))}
      </ul>
    </div>
  );
}
